spring.application.name=uptraceiq-backend

# Connects to an in-memory H2 database named "uptraceiq"
spring.datasource.url=jdbc:h2:mem:uptraceiq

# Tells Spring which Java class handles the connection
spring.datasource.driver-class-name=org.h2.Driver

# Gives us a web UI at localhost:8080/h2-console to browse the database
spring.h2.console.enabled=true

# Used to see the SQL that JPA generates in the console
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true